/**
 * BACKEND (server-to-server) conversion dispatch to the Soborbo event-gateway.
 *
 * Copy this into the Astro site's `src/lib/tracking/` and call it from the API
 * route that receives the form POST. This is the ONLY way the high-value
 * (`server_ingress_only`) conversions — quote_calculator_submitted,
 * callback_request_submitted, contact_form_submitted, order_request_submitted,
 * purchase — reach the gateway: the browser path answers 403 for them
 * (TRK-400-017), because a browser Origin header is spoofable from curl.
 *
 * This module is battle-tested: it is the exact pattern running in production on
 * lomtalan.hu / painlessremovals.com / beautyflow.hu since Run 6 (2026-07).
 *
 * THE FIVE CONTRACTS THIS ENCODES — breaking any of them is a silent money bug:
 *
 *  1. SERVICE BINDING, not fetch. A plain fetch() to https://<your-site>/api/event/*
 *     would NOT reach the gateway: that URL is a Worker route on your OWN zone, and
 *     Cloudflare short-circuits a Worker subrequest that re-enters a route on the
 *     same zone (loop protection). The lead endpoint still returns 200 — the
 *     conversion just vanishes. Bind the gateway worker in wrangler config:
 *       [[services]]  binding = "GATEWAY"  service = "event-gateway"
 *  2. SHARED event_id. `eventId` MUST be the id the browser minted for this same
 *     conversion (the `event_id` hidden form field). A fresh id does not "add" a
 *     conversion — it DOUBLE-COUNTS the lead, because Meta dedupes on
 *     (event_name, event_id).
 *  3. lead_id is the CRM's id — the `id` from the CRM webhook RESPONSE — or absent.
 *     NEVER substitute a site-side fallback (event_id, email hash, timestamp): a
 *     populated-but-unjoinable lead_id is worse than NULL, because NULL is
 *     detectable and a wrong-namespace key is not.
 *  4. Never send value: 0 — Meta logs it as a real value and it skews ROAS. This
 *     module omits value AND currency together when there is no positive value.
 *  5. 400/401/403/404 are NON-RETRIABLE — they are OUR misconfiguration (bad
 *     payload, bad token, missing KV site-config), and retrying cannot fix them.
 *     Fail loud (log + alert), don't loop.
 *
 * BOT GUARD: when your form endpoint silently fake-succeeds on a honeypot or
 * time-check hit, it must return a `silent: true` flag internally and the caller
 * must SKIP this dispatch (and every other tracking sink). A bot "lead" that books
 * a Meta conversion poisons optimization exactly like a lost real one.
 */

/** Minimal shape of the Cloudflare service binding to the gateway Worker. */
export interface GatewayFetcher {
  fetch: (input: string, init?: RequestInit) => Promise<Response>;
}

export interface GatewayEnv {
  /** Service binding to the event-gateway Worker (see contract #1 above). */
  GATEWAY?: GatewayFetcher;
  /** Plaintext per-site token; its SHA-256 is `crm_token_sha256` in the gateway KV
   * site-config (generated by generate-site.mjs → crm-secret.env). */
  TRACKING_GATEWAY_TOKEN?: string;
  /** e.g. https://example.com — the site's own hostname; the gateway resolves the
   * tenant from it (multi-tenant routing). */
  SITE_URL?: string;
  /** Synthetic-lead smoke test — see `resolveTestEventCode` + smoke.ts. */
  TRACKING_TEST_LEAD_EMAIL?: string;
  TRACKING_TEST_EVENT_CODE?: string;
}

export type ConsentSignal = 'GRANTED' | 'DENIED';

export interface ConsentState {
  ad_user_data: ConsentSignal;
  ad_personalization: ConsentSignal;
  ad_storage: ConsentSignal;
  analytics_storage: ConsentSignal;
}

/**
 * Canonical gateway event names a site backend may send (Serverside
 * `src/events.json`: channels include "server", kind ≠ offline). The
 * server-ingress-only five are the usual suspects; the click events are legal
 * here too (e.g. an email-click flow confirmed server-side).
 */
export type GatewayEventName =
  | 'quote_calculator_submitted'
  | 'callback_request_submitted'
  | 'contact_form_submitted'
  | 'order_request_submitted'
  | 'purchase'
  | 'phone_number_clicked'
  | 'email_address_clicked'
  | 'whatsapp_button_clicked'
  | 'begin_checkout'
  | 'video_play';

export interface GatewayUserData {
  email?: string;
  phone_number?: string;
  first_name?: string;
  last_name?: string;
  city?: string;
  postal_code?: string;
  country?: string;
}

export interface GatewayConversionInput {
  eventName: GatewayEventName;
  /** MUST be the browser's event_id for this conversion (contract #2). */
  eventId: string;
  /** The CRM's own record id, or absent (contract #3). */
  leadId?: string;
  value?: number;
  /** 3-letter ISO 4217. REQUIRED whenever value is set — there is no default. */
  currency?: string;
  source?: string;
  userData?: GatewayUserData;
  attribution?: Record<string, string | undefined>;
  consent?: ConsentState;
  eventSourceUrl?: string;
  /** The REAL end-user's IP/UA — without them the gateway would attribute the
   * conversion to our own Worker's egress IP/UA (wrong geo, worse Meta EMQ). */
  clientIpAddress?: string;
  clientUserAgent?: string;
  testEventCode?: string;
}

export interface GatewayResult {
  ok: boolean;
  status?: number;
  error?: string;
  retriable?: boolean;
  attempts: number;
}

// Short on purpose: this runs inside the lead request, so a sick gateway must not
// keep the user staring at a spinner. A genuinely lost event is caught by the
// gateway's own zero-conversion / smoke alerts, not by hammering here.
const DEFAULT_RETRY_DELAYS_MS = [400, 1200];
const defaultSleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

export function gatewayBaseUrl(env: GatewayEnv): string | undefined {
  const raw = env.SITE_URL;
  return raw ? raw.replace(/\/+$/, '') : undefined;
}

export function isGatewayConfigured(env: GatewayEnv): boolean {
  return Boolean(env.TRACKING_GATEWAY_TOKEN && env.GATEWAY && gatewayBaseUrl(env));
}

/**
 * Consent Mode v2 state from the CookieYes cookie — the SAME source, and the same
 * mapping, the browser lib uses (lib/gateway.ts `getConsentState`). Reading it
 * server-side (from the form POST's Cookie header) means the two legs always agree
 * about the user's choice.
 *
 * Returns undefined when the cookie is absent or is not a CookieYes cookie — we do
 * NOT guess. The gateway then applies `require_consent` and fails closed, which is
 * the correct GDPR posture.
 */
export function readConsentFromCookie(cookieHeader: string | null): ConsentState | undefined {
  if (!cookieHeader) return undefined;

  let raw: string | undefined;
  for (const part of cookieHeader.split(';')) {
    const idx = part.indexOf('=');
    if (idx < 0) continue;
    if (part.slice(0, idx).trim() === 'cookieyes-consent') {
      raw = decodeURIComponent(part.slice(idx + 1).trim());
      break;
    }
  }
  if (!raw) return undefined;

  const map: Record<string, string> = {};
  for (const part of raw.split(',')) {
    const idx = part.indexOf(':');
    if (idx > 0) map[part.slice(0, idx).trim()] = part.slice(idx + 1).trim();
  }
  if (map.advertisement === undefined && map.analytics === undefined) return undefined;

  const sig = (yes: boolean): ConsentSignal => (yes ? 'GRANTED' : 'DENIED');
  const adGranted = map.advertisement === 'yes';
  return {
    ad_user_data: sig(adGranted),
    ad_personalization: sig(adGranted),
    ad_storage: sig(adGranted),
    analytics_storage: sig(map.analytics === 'yes'),
  };
}

/**
 * Returns the Meta test-event code iff this lead is the designated synthetic one.
 * Keyed on the lead's address rather than a global "test mode" flag: a global flag
 * (or the gateway's KV `meta.test_event_code` — FORBIDDEN, see generate-site.mjs)
 * also catches every REAL lead that arrives while it is on, quietly routing paying
 * conversions into Meta's Test stream. Keyed this way, a real lead can never be
 * diverted.
 */
export function resolveTestEventCode(env: GatewayEnv, email?: string): string | undefined {
  const marker = env.TRACKING_TEST_LEAD_EMAIL?.trim().toLowerCase();
  const code = env.TRACKING_TEST_EVENT_CODE?.trim();
  if (!marker || !code || !email) return undefined;
  return email.trim().toLowerCase() === marker ? code : undefined;
}

/** Drops undefined/empty entries so we never ship blank PII fields. */
function compact(obj: object): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v !== undefined && v !== null && v !== '') out[k] = v;
  }
  return out;
}

export function buildGatewayPayload(input: GatewayConversionInput): Record<string, unknown> {
  // Contract #4: never send `value: 0`. Omit value AND currency together when
  // there is no positive money value. Currency has NO default — a hardcoded
  // fallback ships the wrong currency the day the module is copied to a site in
  // another market.
  const hasValue =
    typeof input.value === 'number' && Number.isFinite(input.value) && input.value > 0 &&
    typeof input.currency === 'string' && input.currency.length === 3;

  const userData = input.userData ? compact(input.userData) : undefined;
  const attribution = input.attribution ? compact(input.attribution) : undefined;

  return compact({
    event_name: input.eventName,
    event_id: input.eventId,
    event_time: Math.floor(Date.now() / 1000),
    lead_id: input.leadId,
    ...(hasValue ? { value: input.value, currency: input.currency } : {}),
    source: input.source,
    user_data: userData && Object.keys(userData).length > 0 ? userData : undefined,
    attribution: attribution && Object.keys(attribution).length > 0 ? attribution : undefined,
    consent: input.consent,
    event_source_url: input.eventSourceUrl,
    client_ip_address: input.clientIpAddress,
    client_user_agent: input.clientUserAgent,
    test_event_code: input.testEventCode,
    // NOTE: no `turnstile_token`. There is no browser in this call path; the
    // per-site X-Admin-Token is what authorises us.
  });
}

export async function sendGatewayConversion(
  env: GatewayEnv,
  input: GatewayConversionInput,
  opts: {
    fetchImpl?: GatewayFetcher['fetch'];
    sleepImpl?: (ms: number) => Promise<void>;
    retryDelaysMs?: number[];
  } = {},
): Promise<GatewayResult> {
  const base = gatewayBaseUrl(env);
  if (!env.TRACKING_GATEWAY_TOKEN || !base || (!env.GATEWAY && !opts.fetchImpl)) {
    return { ok: false, error: 'gateway_not_configured', retriable: false, attempts: 0 };
  }

  const fetchImpl = opts.fetchImpl ?? ((url, init) => env.GATEWAY!.fetch(url, init));
  const sleepImpl = opts.sleepImpl ?? defaultSleep;
  const delays = opts.retryDelaysMs ?? DEFAULT_RETRY_DELAYS_MS;

  // NOT `/api/event/conversion` — that is the BROWSER path (Origin allow-list +
  // IP rate limit). Server-side conversions all leave from a single Worker egress
  // IP, so the IP-keyed limit would throttle exactly the conversions that carry
  // money. The gateway refuses this route without a valid per-site token.
  //
  // We still address the SITE's own hostname (through the service binding): the
  // gateway resolves the tenant from the request hostname.
  const url = `${base}/api/event/conversion-server`;
  const body = JSON.stringify(
    buildGatewayPayload({
      ...input,
      testEventCode: input.testEventCode ?? resolveTestEventCode(env, input.userData?.email),
    }),
  );
  const headers = {
    'content-type': 'application/json',
    'x-admin-token': env.TRACKING_GATEWAY_TOKEN,
  };

  let attempts = 0;
  let lastError = 'unknown';
  let lastStatus: number | undefined;

  for (let i = 0; i <= delays.length; i++) {
    attempts++;
    try {
      const res = await fetchImpl(url, { method: 'POST', headers, body });
      lastStatus = res.status;

      if (res.status >= 200 && res.status < 300) {
        return { ok: true, status: res.status, attempts };
      }

      // Contract #5: 400 (invalid payload), 401 (bad token), 403, 404 (no KV
      // site-config) are OUR misconfiguration, not a transient fault. Retrying
      // cannot fix them — fail loud instead.
      if (res.status === 400 || res.status === 401 || res.status === 403 || res.status === 404) {
        return {
          ok: false,
          status: res.status,
          error: `gateway_rejected_${res.status}`,
          retriable: false,
          attempts,
        };
      }
      lastError = `gateway_status_${res.status}`;
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
    }

    if (i < delays.length) await sleepImpl(delays[i]);
  }

  return { ok: false, status: lastStatus, error: lastError, retriable: true, attempts };
}
